# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3967930278db473428d761d9c23d8566627acd913f9a8c8c5bf6667701b6c11ef212e5355e09bd4cb080e5ee3980c443ea83262ec7cf31a569f42b7d9bd1cfef

test:
  secret_key_base: 9cd98d3c71670622ad275312b3ba493ff63d6988bf7cc1af67aeaabf1483da793d32bc6437d63e30e2f787542539e2f7d2d967fe15a3b95facefb190eb9b11c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
